### ISSUE TITLE
WASM compatibility

### ISSUE THREAD

**Issue by bryanchriswhite** [LeastAuthority/wormhole-william#2]
As we intend to use this client library in the browser, we require that it (and its dependencies) be compatible with go's WASM support. In the [spike](#1) we learned that we will have to replace the websocket library used, to that end. We also learned that we  may need the use of go's build tags to mutually exclude wasm/non-wasm code for backwards compatibility. I think we'll have to use the wasm tag in our tests as well and ensure we're running tests with and without that tag (in CI/CD and manually in the mean time, perhaps with make).

Size of the wasm module will quickly become a priority as we get further along. I think it would be prudent to keep an eye out for (and avoid creating) places where code is unnecessarily imported or poorly organized, either fixing it as we go or taking note in a card in [MW4All](https://github.com/orgs/LeastAuthority/projects/2). This is going to be the first line of defense when it comes to keeping the output size down. 

To test-drive this, I think we just need to choose a build tool and ensure that we have a task/target for running tests with the wasm tag and without to provide coverage on both builds.

**Comment by vu3rdd** [comment]
Started working on this in the branch [wasm-compat](https://github.com/LeastAuthority/wormhole-william/tree/wasm-compat) branch. Could not cherry-pick @bryanchriswhite's commit that added the `wasm` directory, so had to copy from the head of the `bryan/wasm` branch.

Also added build flags into files, so that existing code compiles fine on non-wasm platforms and wasm modules alone gets pulled for the wasm build.
